* What is the supervenience argument against non-reductive physicalism?

The supervenience argument is based on the exclusion principle (that no event has more than one sufficient cause, except when it’s a genuine case of overdetermination) and the supervenience of mental properties on physical properties (i.e., the idea that no two entities can have different mental properties if they share all their physical properties; in other words, mental properties supervene on physical properties). Then, imagine I’m late for work and decide to call a taxi. By supervenience, there’s a physical state of my brain, P, that suffices for my decision to call a taxi. This implies that my desire not to be late for work cannot cause my decision unless it causes P. (This relies on the supervenience base P ‘screening off’ any other cause: nothing else can be causally relevant to my decision that is not causally relevant to P.) By exclusion, my desire not to be late does not cause P. Conclusion: my desire not to be late does not cause my decision to call a taxi. This argument tells against non-reductive physicalism because it requires us either to accept one of two unpalatable positions (that causal closure is false, or that epiphenomenalism is true), or, more palatably, to reject property dualism (hence, accept reductive physicalism).