* Explain why the state of nature, as discussed by Hobbes, can be understood as a prisoner’s dilemma.

Hobbes conceives the state of nature as a state of permanent war, which he defines as the absence of agreed peace, rather than outright conflict; he describes life in the state of nature as “solitary, poor, nasty, brutish and short”. Hobbes lists the characteristics of the state of nature as Desire (of each to continue getting what they want), Equality (rough equality of physical and mental powers), Scarcity (of goods) and Coincidence (of desire for the same things). Taken together, these lead to conflict on a roughly equal footing, with three main ends: Gain (of resources), Safety (of one’s person and property), and Reputation (social standing).

This situation can be viewed as an iterated prisoner’s dilemma: a repeated “game” in which two participants, on each turn, can choose to cooperate or defect. In the Hobbesian case, cooperation means choosing not to fight, and defection means choosing to fight. Typically, the game is set up so that if both players cooperate, they receive a modest reward (for example, in this case, they share resources); if they both defect, things go fairly badly for both of them (for example, they are both injured, or the resources over which they’re competing are partly spoiled), and if one cooperates while the other defects, then the spoils go to the defector. This modern game-theoretic treatment seems to be a good fit for Hobbes’s conception.