* Explain the difference between political liberalism and liberalism as a comprehensive doctrine.

Rawls’s earlier work “A Theory of Justice” proposes a comprehensive liberal doctrine. A comprehensive doctrine covers every aspect of life, public, private and personal. In his later work “Political Liberalism”, Rawls claims that no comprehensive doctrine is appropriate to be a “political conception” (that is, a free-standing moral conception of a society’s “basic structure”, expressed in terms of fundamental ideas seen as implicit in the political culture of a democratic society) of a society, as it would require oppression of at least some members of the society to maintain its stability (the “Fact of Oppression”), which results in a mere “modus vivendi”, not a truly stable society. To be legitimate, public policy must be justifiable to all citizens. Rawls says this justification can take the form of an “overlapping consensus”, by means of which a society composed of groups with different, incompatible comprehensive doctrines (so long as they are all reasonable) can nonetheless be stable, and achieve “reasonable pluralism”. Rawls asserts that liberalism restricted to the basic structure of society, which he calls “political liberalism”, based on justice as fairness, is an appropriate political conception. He bases political liberalism on his lexically-ordered principles of a guarantee of fair value of political liberties, fair equality of opportunity and the difference principle. In brief, political liberalism is liberalism applied to just the basic structure of society, while liberalism as a comprehensive doctrine is liberalism applied to the entire society.