* Explain Nozick’s Wilt Chamberlain example.

Nozick uses the Wilt Chamberlain example to show how liberty upsets patterning, arguing that any patterned distribution of goods, which uses some measure of desert, fails to account for people’s right to dispose of their property as they wish, the entitlement theory of justice in holdings. The example is this: a famous basketball player, Wilt Chamberlain, signs a one-year contract with his team to receive 25¢ from the price of each home game ticket for that season. Assume that at the start of the season, a just distribution of goods obtains, according to some patterned principle. At the end of the season, assuming that a large number of home game tickets is sold, Wilt Chamberlain’s share of resources will be much greater than it would be under any patterned (or end-state) distribution. To restore such a distribution, the state would have to confiscate some of Chamberlain’s new wealth; but how is that just, when the money came to him voluntarily from the ticket buyers and his club? Nozick concludes that any patterned (or end-state) principle, except perhaps for an extremely weak one, or one that operates by means of an invisible hand, will be violated by voluntary, just transfers of this sort; and that therefore any such principle can only be maintained by unjust confiscation.