* Explain Hume’s problem of induction.

If I drop a stone repeatedly and each time it falls to the ground, I would be fairly certain that it would fall to the ground again if I were to drop it again; but Hume says there is no deductive proof for this; in particular, there would be no logical contradiction if it did not. Instead, we must rely on an inductive proof. But, Hume points out that there is no deductive proof of the validity of induction as a method of reasoning. We can only justify induction based on the fact that it has worked in the past—but that is an inductive proof: it relies on the validity of induction, a circular argument. Therefore, all inductive arguments are ultimately circular. Inference, Hume says, relies on an “unreasoned union of ideas”, namely contiguity, succession, and constant conjunction. To reason inductively, Hume says, we must assume that Nature is uniform; we cannot have certain knowledge that it is, so we must base our reasoning on probability (circular again: to use probability as a justification we must rely on the validity of inductive inference!). In conclusion, the problem, according to Hume, is that the method on which we rely for scientific reasoning (reasoning based on causation) has, and can have, no logical justification: it is as much a hypothesis as the reasoning it supports.