* Give one example that tells against the conformist position about rational disagreement, explaining why it does so.

The conformist holds that there can be no rational disagreement among epistemic peers, and that each should re-evaluate their position and seek agreement, for example by splitting the difference, or withhold belief. Some types of disagreement are problematic for conformism; one is the “Many Against One Problem”. Here is an example: I, a church musician, am discussing with colleagues the striking fact that the first letter of the Hebrew scriptures is ‘ב’ (beth), the second letter of the Hebrew alefbet. We are epistemic peers: we all have the quick intelligence and retentive memories required by our profession and the knowledge of scriptures and Biblical languages that one picks up over many years in church music; and we are all well-rested and alert for the day’s carol service. One of us, say Taf, pipes up and says this is not so: the first letter of Genesis is really א (aleph), the /first/ letter of the alefbet, as is only logical. Being musicians, not priests, we do not have a Bible to hand in the vestry. But conformism seems wrong here: it would make no sense to think perhaps the first letter is between aleph and beth; and why should we all withhold belief on a matter that many of us have independently verified in the past, with reference to a Bible or Hebraist? The rational conclusion for the rest of us seems to be that Taf is simply mistaken about the matter of fact.