* Explain Peter Singer’s principle of equal consideration of interests.

Singer’s principle is an attempt to provide an egalitarian basis for treating people, avoiding the problem that people are clearly different by abstracting from individuals and instead considering their interests. Singer says that individuals deserve equal moral regard because their interests are the same. “Interests” are basic fundamental needs: food, water and other essential resources; to avoid pain and suffering; health; close personal relationships—things that any human needs to live a good life. The principle is that the most important interests deserve equal consideration despite other inequalities, independent of an individual’s characteristics.

Some other thinkers argue that it’s impossible to divorce an individual’s interests from other traits of their psychology; for example, if A has a higher tolerance of pain than B, then we may consider that their interests to avoid pain are not equal. The principle does not imply equal treatment (that is, an egalitarian distribution of resources aiming for equality of outcome): for example, if a surgeon can save C’s leg (and C has two legs) or D’s toe (and D has only one leg), then the principle suggests that C’s interest is greater than D’s, and the surgeon should save C’s leg, leaving C with two legs while D loses a toe on their remaining leg.