* With the help of an example, explain one way in which Sophia Moreau argues that discrimination is unjust because it restricts people’s freedom.

Moreau argues that indirect discrimination unjustly restricts people’s autonomy, or positive freedom; not as a result of actions that directly discriminate against individuals, but as the accumulation of discrimination across a community. Here is an example: suppose that a particular housing developer decides to build affordable housing by building a block of flats that has fifty percent more floors vertically than normal. The rooms are only two metres from floor to ceiling. This indirectly discriminates against tall people, who cannot comfortably move around (as they would bang their heads) or, in some cases, even stand up. The discrimination is indirect, because there is no ban on tall people living in the flats; it is merely extremely uncomfortable for them to do so. Tall people will have to find more expensive accommodation, move to a cheaper area, or never get out of bed. This restricts their positive freedom to decide where to live, how much to spend on accommodation, and how active a lifestyle they wish to lead, compared to the shorter majority who can comfortably live in the truncated apartments. Moreau argues that is it this restriction of freedom that makes the discrimination unjust.